# Generated by Django 5.1.7 on 2025-03-09 11:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Studinfo',
            fields=[
                ('studid', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=20)),
                ('rollno', models.IntegerField()),
                ('gitlink', models.URLField()),
            ],
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('Subjectcode', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=30)),
                ('credits', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='college',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Qualification', models.CharField(max_length=50)),
                ('studid', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='Home.studinfo')),
            ],
        ),
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('TeacherID', models.IntegerField(primary_key=True, serialize=False)),
                ('Qualification', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=50)),
                ('subjectcode', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Home.subject')),
            ],
        ),
    ]
